spring:
  application:
    name: eureka-server

server:
  port: 8302

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  prefix: /api
  routes:
    address-service:
      path: /address-service/**
      url: http://localhost:8301